#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 27 17:39:50 2022

@author: everto
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage

img=cv2.imread("bananos.jpg")

cv2.imshow("original", img)

# kernel_3x3=np.ones((3,3), np.float32)/(3*3)
# output=cv2.filter2D(img,-1,kernel_3x3)
# cv2.imshow("3*3", output)

# kernel_5x5=np.ones((5,5), np.float32)/(5*5)
# output_5=cv2.filter2D(img,-1,kernel_5x5)
# cv2.imshow("5*5", output_5)

output=cv2.GaussianBlur(img, (21,21), 0)
cv2.imshow("3*3", output)